### ISSUE TITLE
Error when try config

### ISSUE THREAD

**Issue by katinbox** [gorbit99/codewindow.nvim#1]
I got a error message:

![2022-10-18_08-25](https://user-images.githubusercontent.com/43630437/196313947-175f9373-2172-4533-b1e0-5ee3f5a14c30.png)

**Comment by gorbit99** [comment]
This seems to be a change in treesitter somewhere, I'll try to deal with it asap

**Comment by gorbit99** [comment]
Fixed by https://github.com/gorbit99/codewindow.nvim/commit/4311ad3aa4042868b676d4a3bfd4526fb6b61618
Issue was https://github.com/nvim-treesitter/nvim-treesitter/issues/2293#issuecomment-1279974776
