### ISSUE TITLE
Winbar makes codewindow too high

### ISSUE THREAD

**Issue by Kibadda** [gorbit99/codewindow.nvim#11]
Hi,

I have `winbar` enabled in my neovim config.
Unfortunately this makes the codewindow one line too high and so my statusline gets covered by it.

With winbar enabled:
![grafik](https://user-images.githubusercontent.com/71396679/196442608-f433c8f0-ddb5-4a1e-a539-fd6c829e213e.png)

Without winbar:
![grafik](https://user-images.githubusercontent.com/71396679/196443447-a7fb89c7-4277-47d1-a242-024d71d0bfd9.png)

**Comment by nyngwang** [comment]
@gorbit99 Would it be possible to customize the height of the codewindow/minimap, say 80% height?

**Comment by gorbit99** [comment]
> @gorbit99 Would it be possible to customize the height of the codewindow/minimap, say 80% height?

I would've preferred a separate issue for this, but both of them are now fixed in b76c2fd9888123a4cddb666cc4f8a8bc8abcacf4

**Comment by Kibadda** [comment]
Really nice. Thank you very much.
