### ISSUE TITLE
Codewindow affects the packer.nvim lazy load

### ISSUE THREAD

**Issue by dhruvinsh** [gorbit99/codewindow.nvim#12]
As title says, if I fire the codewindow first and try to to load lazy-loaded plugin for example NvimTree or Neogit it will never works.
Steps to reproduce:
* lazy load some plugin
* fire codewindow (\<leader\> m m)
* try to open lazy load plugin (for example :NvimTreeToggle) will end in error, `E492: Not an editor command: NvimTreeToggle`

**Comment by gorbit99** [comment]
That's strange, I'll check it out, thanks for the report

**Comment by gorbit99** [comment]
Just saw, that I was accidentally clearing all groupless autocommands, check, if the problem still occurs
