### ISSUE TITLE
Using vim-illuminate makes unexpected highlights on minimap

### ISSUE THREAD

**Issue by nick4tech** [gorbit99/codewindow.nvim#14]
I'm currently using https://github.com/RRethy/vim-illuminate which uses treesitter and lsp to highlight other ocurrences of the word under the cursor on the document:

![image](https://user-images.githubusercontent.com/6836442/196548822-4a996dd6-7c66-414a-835a-e2b3e6d79f7d.png)

This is causing a strange highlight behaviour on the minimap, where it highlights other sections with similar braille patterns than were the cursor is currently:

![image](https://user-images.githubusercontent.com/6836442/196549035-051aabfb-2a8e-4cc7-9bab-c88cb32ec7dd.png)

![image](https://user-images.githubusercontent.com/6836442/196549252-2a81aa06-0d66-47c1-aead-c99c7ae9bd58.png)

This feature should be disabled while the cursor is on the minimap.

**Comment by gorbit99** [comment]
Made the minimap buffer have the Codewindow filetype, so you can now ignore it in illuminate.
https://github.com/gorbit99/codewindow.nvim/commit/383042d957825dd1afc8656d99fcc24484c1a9b0

**Comment by nick4tech** [comment]
Great! Thanks!
