### ISSUE TITLE
[FEATURE REQUEST] Cursor position

### ISSUE THREAD

**Issue by grappas** [gorbit99/codewindow.nvim#15]
Could be toggleable via setup.

**Comment by gorbit99** [comment]
I'll give it a go

**Comment by elliotwesoff** [comment]
I was just going to make this FR. I'll give it a go too!

**Comment by gorbit99** [comment]
> I was just going to make this FR. I'll give it a go too!

I haven't yet started this up, should I take this as you wanting to implement it?

**Comment by elliotwesoff** [comment]
I did take a look around the repo, but since I'm still pretty new to Lua and neovim I didn't know where to start. Seems like it was easy enough for you though!
