### ISSUE TITLE
Codewindow not working well with Neotree

### ISSUE THREAD

**Issue by ASoldo** [gorbit99/codewindow.nvim#16]
When I toggle minimap in my current buffer it shows on right side as expected. then i open Neotree to browse my files and now in that buffer i see minimap. It dissapear from my code buffer and appear in other buffer that should not have it (like file explorer).
Other visual problem I have is that in my code buffer minimap bottom is overlapping with status bar (it covers bottom right corner) so I can't see percentage for file, TS icon.

Other than that I see no other major issues. Nice work!

**Comment by gorbit99** [comment]
Could this be a mix of https://github.com/gorbit99/codewindow.nvim/issues/11 and https://github.com/gorbit99/codewindow.nvim/issues/3 by any chance? The latter is already solved, the former I'm working on

**Comment by ASoldo** [comment]
Oh nice, waiting for #11 then.
