### ISSUE TITLE
[ UNWANTED BEHAVIOUR ] Some buffers that shouldn't be affected by this plugin

### ISSUE THREAD

**Issue by grappas** [gorbit99/codewindow.nvim#17]
Like... all non-file related buffers:
terminal:
![image](https://user-images.githubusercontent.com/1036957/196764661-450527bc-5860-4c85-b5c7-16145e22bf24.png)
NeoTree:
![image](https://user-images.githubusercontent.com/1036957/196764852-7a1ebc35-14ea-4529-aa68-19782dc34a55.png)

**Comment by gorbit99** [comment]
See #3

**Comment by grappas** [comment]
Unfortunately It's not working so well with terminals:
![obraz](https://user-images.githubusercontent.com/1036957/196802526-e6267dcd-f216-49ec-8b68-dc31db750b00.png)
It works well with neo-tree, but don't seem to bother with term or zsh.
```
({
                exclude_filetypes = {
                    'neo-tree',
                    'term',
                    'zsh',
                    'powershell',
                    'Powershell',
                    'powershell.exe',
                    'Powershell.exe'
                }
            })
```
![obraz](https://user-images.githubusercontent.com/1036957/196803181-f0dbf3c3-5de1-459d-96a3-fc2d95b68094.png)
![obraz](https://user-images.githubusercontent.com/1036957/196803232-564b2f1d-1bf6-4ab3-8e8d-5e4752d9a72b.png)

**Comment by grappas** [comment]
@gorbit99

**Comment by gorbit99** [comment]
Added in a config option, "active_in_terminals", by default false, it does what it says on the tin
