### ISSUE TITLE
[Feature] Allow configuring the window's appearance

### ISSUE THREAD

**Issue by akinsho** [gorbit99/codewindow.nvim#19]
It would be nice if the user could change some simple things about the window, e.g.

- the window border style
- the window highlights etc.

<img width="285" alt="image" src="https://user-images.githubusercontent.com/22454918/196897633-6128f1b7-3809-4113-8404-0c9796b06210.png">

For example, in my case I change the border of all floating windows by all plugins to match my desired custom window border and tweak the highlights to match, but currently this isn't possible.
Also, as you can see in the screengrab the signcolumn is coloured which is probably because I highlight the background of diagnostic signs but not the sign column itself, but the highlights are probably taken from the signs themselves

**Comment by gorbit99** [comment]
> For example, in my case I change the border of all floating windows by all plugins to match my desired custom window border and tweak the highlights to match, but currently this isn't possible.
For now you can work around this by defining a highlight named CodewindowBorder before you open the minimap (so probably before setup).

> but the highlights are probably taken from the signs themselves
Indeed, they are just DiagnosticSignWarn and DiagnosticSignError. I'll probably put in highlight groups that by default link to these two, but can be overwritten.

**Comment by akinsho** [comment]
Sounds great @gorbit99, tbh I meant the highlight specifically, but both are good since generally I change the border of all my floating windows to a custom style and since it's not currently possible to do this at the vim level it's good to have the option in a plugin

**Comment by gorbit99** [comment]
Added in https://github.com/gorbit99/codewindow.nvim/commit/b412f022df7282ef91d922385c62c58bb9b03d0e

You can change the highlights by defining the highlight groups CodewindowBackground, CodewindowBorder, CodewindowWarn and CodewindowError, and you can change the border style with the window_border config option

**Comment by gorbit99** [comment]
> @gorbit99 I just tested this out and I don't think it works for the code window border because that highlight is used for `VertSplit` in the winhighlight not for the `FloatBorder`. I think `VertSplit` should be changed to `FloatBorder` since atm the `CodewindowBorder` highlight does not affect the border highlight

Ah, actually, I did test it and it worked, but it's probably because FloatBorder (in my case) is linked to VertSplit. I'll change it to that in a sec.

**Comment by akinsho** [comment]
Awesome that works great now 👍🏿

**Comment by Integralist** [comment]
👋🏻 Sorry I wasn't able to follow along that well, but I didn't want to open a separate issue just in case my issue was related.

In the below screenshot you can see that some dots have highlights (at the top some are green, a little bit below that there are some orange and blue dots) and I'm not sure why?

<img width="1920" alt="Screenshot 2022-10-26 at 09 27 21" src="https://user-images.githubusercontent.com/180050/197975993-bfcb39d6-ab36-412b-bcaa-e510147808b2.png">

In other files this can be a bit more distracting...

<img width="1920" alt="Screenshot 2022-10-26 at 09 35 06" src="https://user-images.githubusercontent.com/180050/197976777-bf9a7843-6fa3-42ad-9034-558482dc969f.png">

Now at first, I thought maybe the dots were being coloured somehow in relation to the code syntax highlighting but now I think this actually has something to do with highlight groups (as I'm guessing the dots are using some kind of diagnostic 'sign' symbol maybe).

Is this the case? How can I get rid of these additional colours if they are indeed meaningless in relation to what minimap is displaying (don't want to break any diagnostic stuff that my current buffer's LSP might be using for example).

Thanks!

**Comment by gorbit99** [comment]
@Integralist Please open a new issue, it's better to close that in case it is related, than dealing with separate issues in the same bugreport
