### ISSUE TITLE
 packer.nvim: Error running config for codewindow.nvim: [string "..."]:0: attempt to call field 'apply_default_keybindings' (a nil value)

### ISSUE THREAD

**Issue by nyngwang** [gorbit99/codewindow.nvim#2]
Well... I think we don't have any string including `apply_default_keybindings` in this Repo., so this is a reasonable error.

**Comment by gorbit99** [comment]
Typo, should be apply_default_keybinds()
I'll get it fixed in the readme

**Comment by nyngwang** [comment]
@gorbit99 While this issue is closed, I think the original naming is better than the `keybinds` one.
