### ISSUE TITLE
Remove the screenshots from your Git index

### ISSUE THREAD

**Issue by phaazon** [gorbit99/codewindow.nvim#26]
That is more non-needed bandwidth taken when people will install your plugins in Neovim!

**Comment by gorbit99** [comment]
Where to store them then?

**Comment by phaazon** [comment]
You can open an issue in any github repository and drag and drop the image there. It will generate a link for you.

**Comment by gorbit99** [comment]
Fixed in https://github.com/gorbit99/codewindow.nvim/commit/dad18164f8c53dbc59670187cdd4f250f4f1c4af
