### ISSUE TITLE
[Feature Request] Git changes on the Minimap

### ISSUE THREAD

**Issue by hatredholder** [gorbit99/codewindow.nvim#28]
Adding highlight of changes reported by Git on the Minimap would be lovely. Is there a chance this is ever going to be added?

I was thinking of maybe highlighting the changes the way [wfxr/minimap.vim](https://github.com/wfxr/minimap.vim) does with the **g:minimap_git_colors** option.

Here's how it looks with that option enabled:
![image](https://user-images.githubusercontent.com/86254474/197826751-a7ded506-62c5-4157-90cd-51f8826c168b.png)
The purple highlighted line is the one with Git changes on it.

**Comment by gorbit99** [comment]
I'm looking into this, what I want to achieve is two rows of additional dots, one for deletions and one for additions. It's actually in the TODO list.

**Comment by hatredholder** [comment]
> I'm looking into this, what I want to achieve is two rows of additional dots, one for deletions and one for additions. It's actually in the TODO list.

Sounds promising!  Waiting **real** patiently now. :partying_face:

**Comment by gorbit99** [comment]
Hope you're real patient, because I'm kinda busy. I can start working on it on sunday at the earliest

**Comment by hatredholder** [comment]
> Hope you're real patient, because I'm kinda busy. I can start working on it on sunday at the earliest

No need to rush, take all the time it takes.

**Comment by gorbit99** [comment]
Should now be a thing in the latest commit
![image](https://user-images.githubusercontent.com/5338164/198934269-980bf2c3-9f44-458e-9152-aa22b748ad2a.png)
