### ISSUE TITLE
Onedark Plugin highlights override Codewindow's

### ISSUE THREAD

**Issue by Xemptuous** [gorbit99/codewindow.nvim#30]
I am using `navarasu/onedark.vim` colorscheme, and with it, I am unable to change CodeWindow's color manually.
The highlight group named in `onedark/highlights.lua` uses `FloatBorder` to change the borders of the window instead of Codewindow's built-in `CodewindowBorder` and `CodewindowBackground`.

Something interesting happens with this plugin though.
 
When setting the custom highlights:
```
vim.api.nvim_set_hl(0, 'CodewindowBorder', {fg = '#ffff00'})
vim.api.nvim_set_hl(0, 'CodewindowBackground', {fg = '#ffff00'})
```
I do not get the expected outcome. Instead, I get some random chunks inside the window being colored (mostly "grey" parts in this example), and the border being unaffected.

For now I am using `vim.api.nvim_set_hl(0, 'FloatBorder', {fg = '#4fa6ed'})` (this also works for `bg`)
Highlights Disabled  |  Highlights Enabled | FloatBorder used
:-------------------------:|:-------------------------:|:-------------------------:|
![image](https://user-images.githubusercontent.com/99044751/197947441-1313eee2-d04b-48ce-8d02-c8fef0b08f86.png) | ![image](https://user-images.githubusercontent.com/99044751/197947482-ee09e05f-716d-4866-b4b6-be1b73d10adf.png) | ![image](https://user-images.githubusercontent.com/99044751/197951906-bc4268c0-06a4-419e-ab33-8af4b4656b42.png)

**Comment by gorbit99** [comment]
Try linking the CodewindowBorder and CodewindowBackground highlight groups to the relevant ones from the highlighting.

> I do not get the expected outcome. Instead, I get some random chunks inside the window being colored (mostly "grey" parts in this example), and the border being unaffected.

It's actually probably because "CodewindowBackground" gets used for the dots that do not get any highlight at all. So don't set the foreground to yellow, instead set it to whatever you want those to appear as.

**Comment by gorbit99** [comment]
Any change on this?
