### ISSUE TITLE
Question: is it possible to change colour of horizontal bars?

### ISSUE THREAD

**Issue by Integralist** [gorbit99/codewindow.nvim#32]
Hi 👋🏻 

The two horizontal bars that signify where in the file you are appear to be picking up colours from my current colourscheme...

<img width="180" alt="Screenshot 2022-10-26 at 09 37 36" src="https://user-images.githubusercontent.com/180050/197977355-1baa4124-cccc-41a1-bba8-55e253e1f2ca.png">

Is it possible to manually change those? I'm guessing using a specific highlight group.

**Comment by Integralist** [comment]
OK thanks I'll have a play around with that highlight group.

**Comment by Integralist** [comment]
Hmm, interesting that some of the dots also changed to red?

<img width="963" alt="Screenshot 2022-10-26 at 10 24 16" src="https://user-images.githubusercontent.com/180050/197989142-acf9366a-b50c-43c0-91b6-360bbef60147.png">

**Comment by gorbit99** [comment]
Yeah, same reason, there can only be one foreground color on a character, and it's either the line or the dots. Originally I just bit the bullet and let the line take up different colors, because it was the least bad of the two.

**Comment by gorbit99** [comment]
You can maybe try setting guisp, there's a chance it works in your terminal for underlines

**Comment by Integralist** [comment]
No that's fine, I'm going to disable treesitter as suggested in your comment in https://github.com/gorbit99/codewindow.nvim/issues/33#issuecomment-1291750376

I thought treesitter would be providing something useful but as it turns out the extra colours were just noise. I did recall seeing the setting when originally installing this plugin, but by the time I came to open this issue I forgot about it (apologies for the noise).
