### ISSUE TITLE
I'm not sure what the dot colours represent

### ISSUE THREAD

**Issue by Integralist** [gorbit99/codewindow.nvim#33]
👋🏻

In the below screenshot you can see that some dots have been coloured (e.g. at the top some are green, a little bit below that there are some orange and blue dots) and I'm not sure why? 

<img width="1920" alt="Screenshot 2022-10-26 at 09 27 21" src="https://user-images.githubusercontent.com/180050/197975993-bfcb39d6-ab36-412b-bcaa-e510147808b2.png">

In other files this can be a bit more distracting...

<img width="1920" alt="Screenshot 2022-10-26 at 09 35 06" src="https://user-images.githubusercontent.com/180050/197976777-bf9a7843-6fa3-42ad-9034-558482dc969f.png">

I don't know if this is an mistake on the part of the plugin? (e.g. it's using highlight groups set by my current colour scheme) or if the colours are supposed to represent something? (e.g. it's some kind of treesitter parsing and it's trying to use the same syntax colours as the buffer content). 

I'm guessing the dots are using some kind of diagnostic 'sign' symbol maybe.

Is this the case? How can I get rid of these additional colours if they are indeed meaningless in relation to what minimap is displaying (don't want to break any diagnostic stuff that my current buffer's LSP might be using for example).

Thanks!

**Comment by gorbit99** [comment]
I mean, the whole raison d' etre of this plugin was that it integrates into lsp and treesitter and shows all kinds of stuff on it. You can turn the treesitter coloring off by using putting use_treesitter = false into your config. It's explained in detail in the readme
