### ISSUE TITLE
Make the background gray except for the current page

### ISSUE THREAD

**Issue by sassanh** [gorbit99/codewindow.nvim#36]
It would be nice if the background of the minimal was dimmed except for the current page. Maybe as an option or a separate highlight the user can set.

<img width="376" alt="Screenshot 2022-10-29 at 04 36 48" src="https://user-images.githubusercontent.com/1270688/198755875-8c56cf70-3cf8-4ce8-849e-2da7ad81e068.png">

**Comment by gorbit99** [comment]
Will try to implement this as an alternative to the two lines

**Comment by nyngwang** [comment]
@sassanh Did you achieve this?

**Comment by sassanh** [comment]
@nyngwang No, I didn't.

**Comment by luckasRanarison** [comment]
Duplicate of #46, I think we can close this as it is completed

**Comment by sassanh** [comment]
Yes, thanks!
