### ISSUE TITLE
[Feature Request] Cursor highlight group

### ISSUE THREAD

**Issue by tis-rpage** [gorbit99/codewindow.nvim#39]
Could a cursor highlight group be added to change the text color for the braille on the lines the cursor covers.

How the cursor location is set is great, but adding a means of highlighting the entire set of lines where the cursor is would add more emphasis.

e.g.

vim.api.nvim_set_hl(0, "CodewindowCursor",             {link="ContentCursor"})

<img width="169" alt="image" src="https://user-images.githubusercontent.com/47879216/199237710-f92b0799-8f8e-473a-9c40-b518ea26a0cf.png">

**Comment by gorbit99** [comment]
This should probably be merged with #31, could you add a comment there with the idea instead?
