### ISSUE TITLE
Exclude Minimap in NvimTree

### ISSUE THREAD

**Issue by LSleutsky** [gorbit99/codewindow.nvim#40]
Is there some sort of config where the minimap does not show up whenever the plugin nvimtree is open? Right now I have the minimap show up autmatically only in certain file types, thru the `auto_enable` setting. But whenever I open nvimtree, the minimap moves from the current buffer, into the nvimtree window (_and obviously covers most of it, since it's just a side bar type of file explorer, and not wide at all_).

Is there anything I can do to prevent the minimap from appearing in the nvimtree pane/window? I'm not sure if I can put something into `exclude_filetypes` that would accomplish this, but not effect the minimap from opening in files that I do want.

Thanks!

**Comment by gorbit99** [comment]
Yes, that's what exclude_filetype is for.
Go into the nvimtree buffer, run :set filetype?, and whatever it outputs is what should be put into the exclude filetype table.
