### ISSUE TITLE
[Feature Request] Minimap for strict buffers only

### ISSUE THREAD

**Issue by BooleanCube** [gorbit99/codewindow.nvim#43]
I started using the codewindow.nvim plugin in Neovim and so far I love it. But there is one drawback which is very annoying.
I use Nvim-Tree plugin which is essentially a file explorer plugin embedded in Neovim and soon as I switch buffers to open a new file the codewindow also shifts and displays the minimap of the nvim-tree plugin buffer. Can we make the minimap such that it doesn't shift buffers when moving through multiple buffers as well? Or atleast some how filter some types of buffers from having the minimap?

**Comment by gorbit99** [comment]
Check out #40 for now. I'll consider the feature request during the rewrite that is happening right now.
