### ISSUE TITLE
[ Feature Request ] render current window like vscode

### ISSUE THREAD

**Issue by NEX-S** [gorbit99/codewindow.nvim#46]
Currently codwindow.nvim just renders the window border

![image](https://user-images.githubusercontent.com/97107165/212551194-62059d6d-5c17-416b-a5a2-b268d3f51ea7.png)

I'm wondering if can render the current window as an entire grey area like the pic behave

**Comment by gorbit99** [comment]
I'll have to look into it, off the top of my head I don't think there's anything preventing it from being a thing. Currently I'm a bit busy with life stuff, and at the same time I'm rewriting the plugin to be a bit easier to develop and less error prone. I'll try to make sure this feature gets into that then.

**Comment by sho-87** [comment]
yes this would be awesome to see, as the current border lines can be quite difficult to see quickly
