### ISSUE TITLE
Is it possible to add this option?

### ISSUE THREAD

**Issue by nyngwang** [gorbit99/codewindow.nvim#5]
it will be cool if you could provide an option like `auto_enable` to open the minimap whenever the cursor moves into a buffer of a filetype that is not in the list `exclude_filetypes`.

**Comment by gorbit99** [comment]
That's an interesting idea. I'll see what I can do.

**Comment by dsully** [comment]
Related - it shouldn't open when there are excluded buffer types either (which isn't currently a supported config option).

**Comment by gorbit99** [comment]
Should be in 
https://github.com/gorbit99/codewindow.nvim/commit/6a7ee60db5ead56eb540520214989efa847936e8

**Comment by cshuaimin** [comment]
> `for _, v in config.auto_enable`

You need to call `ipairs` on the table.

**Comment by gorbit99** [comment]
Oh, you're right, will fix it once I'm home (though I appreciate a pr as well)

**Comment by gorbit99** [comment]
Resolved in https://github.com/gorbit99/codewindow.nvim/commit/ef04d2c9e67d28de340077627383405a3da51b4a
