### ISSUE TITLE
Feature/Idea: Only enable if 1 non-excluded filetype window is open

### ISSUE THREAD

**Issue by amaanq** [gorbit99/codewindow.nvim#50]
Say I have neo-tree open to my left (disabled codewindow here), and I have a main window with codemap to my right. Now, I might split to my right for a bit, in that time period while there's more than 1 window with code open, I'd like codewindow to be disabled as it gets too cluttered and hard to read code then with multiple split windows. I wonder if you have an easy way to do this, I'm sure this can be done in a hacky programmatic way in my config, but I'd rather not and see if you have a simple fix/autocmd suggestion :) 

Thanks,
Amaan

**Comment by gorbit99** [comment]
Stuff like this will probably be addressed in the rewrite that's going on currently. I been a bit busy the past few months, but stuff's letting up, so I'll hopefully be able to finish it soon. I'l take this suggestion into account!

**Comment by amaanq** [comment]
Glad to hear! Thanks again

**Comment by amaanq** [comment]
Another issue to think about if you can is that when writing text, if it goes to the end of the line codewindow hides that, and you can't see what you're typing. Codewindow should hide if the cursor is underneath it

**Comment by gorbit99** [comment]
This is somewhat covered by issue https://github.com/gorbit99/codewindow.nvim/issues/20
