### ISSUE TITLE
Feature: let users configure events

### ISSUE THREAD

**Issue by Pocco81** [gorbit99/codewindow.nvim#51]
Codewindow tends to be very slow (at least on my machine) while editing big files (800+ LOC). This is particularly noticeable when typing. I read through the source code, and found that the Codewindow in being update on `TextChanged` (relevant file: https://github.com/gorbit99/codewindow.nvim/blob/master/lua/codewindow/window.lua#L94)

I would like to be able to customize all (or to the very least, the one I mentioned above) event(s), mainly those that trigger Codewindow's updates. This shouldn't be that hard to implement.

An alternative solution (though not the best option) could be to delete these augroups and define them myself (on my config):
```lua
vim.api.nvim_del_augroup_by_name("CodewindowAugroup")
llocal augroup = vim.api.nvim_create_augroup('CodewindowAugroup', {})
-- .. define the autocmds to my liking 
```

**Comment by gorbit99** [comment]
Great suggestion. I'll try to work it into the non-wip version in a bit.

**Comment by Pocco81** [comment]
Awesome, thanks!
