### ISSUE TITLE
Is it possible that this plugin can work with floating window?

### ISSUE THREAD

**Issue by nyngwang** [gorbit99/codewindow.nvim#6]
I'm the author of [NeoZoom.lua](https://github.com/nyngwang/NeoZoom.lua), which is a plugin that will open the current buffer into a floating window. I will be happy to see that it can work with codewindow.nvim :) Currently it looks like this:

Before zoom-in:

<img src="https://user-images.githubusercontent.com/24765272/196332819-7524e442-6606-4126-a146-4c0be0172106.png" width="500">

After zoom-in: As you can see the minimap is not shown (or maybe it's shown but covered by the floating window created by NeoZoom.lua)

<img src="https://user-images.githubusercontent.com/24765272/196332921-09316297-9914-4270-bea5-16e0f40d57b3.png" width="500">

If there is possible to adjust the z-index of the minimap (considering it's also a floating window?), maybe it would be a good idea for users to customize the z-index.

**Comment by gorbit99** [comment]
Currently it has a z-index of 1, specifically for the reason of not showing the minimap if somehow it ended up being displayed on a floating window, but sure, this seems simple enough.

**Comment by gorbit99** [comment]
https://github.com/gorbit99/codewindow.nvim/commit/ad9ec2402307911e9df2f1802f93c9a952e28de2 should introduce this feature, give it a try and see if it works with your usecase

**Comment by nyngwang** [comment]
@gorbit99 Oops, I was trying to solve it before I saw your update. Maybe you could accept my PR since `z_index` can be omitted from the `config = {...}`.

**Comment by gorbit99** [comment]
It can, but it has a default value of 2, if it is. I closed the pr because it didn't bring anything else to the table https://github.com/gorbit99/codewindow.nvim/commit/ad9ec2402307911e9df2f1802f93c9a952e28de2 wasn't already

**Comment by nyngwang** [comment]
OK, it's up to you :) But any non-existing keys in a lua table are actually set to `nil` by default. i.e. I didn't mean to let users set to `nil` explicitly, but instead users can omit `z_index` when they just want the default.

**Comment by gorbit99** [comment]
It can, check out setup in codewindow.config. I merge the given config table and the defaults, so if anything isn't present, it will be set to the default.
