### ISSUE TITLE
Error: /nvim/lazy/codewindow.nvim/lua/codewindow/highlight.lua:241: Invalid buffer id: 51

### ISSUE THREAD

**Issue by nyngwang** [gorbit99/codewindow.nvim#61]
```zsh
Error executing vim.schedule lua callback: ...e/nvim/lazy/codewindow.nvim/lua/codewindow/highlight.lua:241: Invalid buffer id: 51
stack traceback:
	[C]: in function 'nvim_buf_clear_namespace'
	...e/nvim/lazy/codewindow.nvim/lua/codewindow/highlight.lua:241: in function 'display_cursor'
	...local/share/nvim/lazy/codewindow.nvim/lua/codewindow.lua:17: in function ''
	vim/_editor.lua: in function ''
	vim/_editor.lua: in function <vim/_editor.lua:0>
```

It might be that some API calls can be protected by checking whether or not it's valid using `nvim_buf_is_valid`.

https://github.com/gorbit99/codewindow.nvim/assets/24765272/a9c34d2e-6644-419c-b014-2c6131fa6feb

These are the two `autocmd`s I used in the DEMO: (with the augroup name removed.)

```lua
-- if I remove the first one then the error disappear, but then the minimap will not be closed.
vim.api.nvim_create_autocmd({ 'WinLeave', 'TermEnter' }, {
  callback = vim.schedule_wrap(function ()
    require('codewindow').close_minimap()
  end)
})
vim.api.nvim_create_autocmd({ 'CursorHold' }, {
  callback = vim.schedule_wrap(function ()
    if vim.api.nvim_win_get_config(0).relative == 'editor'
      and vim.api.nvim_buf_is_valid(0)
    then
      pcall(require('codewindow').open_minimap)
    end
  end)
})
```

**Comment by gorbit99** [comment]
I'm curious, what are you trying to achieve with these autocommands?

**Comment by nyngwang** [comment]
> [...], what are you trying to achieve with these autocommands?

Basically `active_in_terminals = false` + `auto_enable = true`, but the latter is buggy (it produce a similar error about invalid something, so I decided to do it myself)

---

I just resolved after some trying:

```lua
vim.api.nvim_create_autocmd({
  'TermEnter', 'TermOpen',
  'BufLeave'
}, {
  group = curfile_augroup,
  callback = function ()
    require('codewindow').close_minimap()
  end
})
vim.api.nvim_create_autocmd({ 'BufEnter' }, {
  group = curfile_augroup,
  callback = vim.schedule_wrap(function ()
    if vim.api.nvim_win_get_config(0).relative == 'editor' then
      require('codewindow').open_minimap()
    end
  end)
})
```

**Comment by gorbit99** [comment]
Try putting in the terminal's filetype into the "exclude_filetypes" table. If you are using floaterm, this would be floaterm, but ymmv. auto_enable iirc works off of that table

**Comment by nyngwang** [comment]
It doesn't work, and `exclude_filetypes` cannot be used to differentiate floating/non-floating windows. In my case, I added `fzf` for fzf-lua but it's unrelated to my error since the error was caused by `require('codewindow').close_minimap()`.

**Comment by gorbit99** [comment]
Interesting, anyways, if you could solve the problem, that's great. The project is very much in need of a proper rewrite anyways, I'll see what I can do then.
