### ISSUE TITLE
Request to Add a License to the Repository

### ISSUE THREAD

**Issue by Isrothy** [gorbit99/codewindow.nvim#77]
I find your project very useful and would like to contribute to it. However, I noticed that the repository does not have a license. Without a license, it's unclear how others can use, modify, or distribute the code.

Would you be willing to add a license to clarify the terms under which the code can be used? The MIT License or Apache 2.0 License are commonly used and permissive options that you might consider.

**Comment by gorbit99** [comment]
Thank you for the observation, didn't know that it didn't have a license!
