### ISSUE TITLE
Moving to a different window whilst the minimap is open throws a cursor position error

### ISSUE THREAD

**Issue by akinsho** [gorbit99/codewindow.nvim#9]
Hi, 

Great plugin 👍🏿 

Just tried it out and noticed that when I open the minimap in one window then open another split and change buffer it throws the error below. Keeping the window open and having it automatically switch/render the new buffer doesn't seem to work currently.

```
Error executing vim.schedule lua callback: ...acker/start/codewindow.nvim/lua/codewindow/highlight.lua:176: Cursor position outside buffer                                                      
stack traceback:                                                                                                                                                                                
        [C]: in function 'nvim_win_set_cursor'                                                                                                                                                  
        ...acker/start/codewindow.nvim/lua/codewindow/highlight.lua:176: in function 'display_screen_bounds'                                                                                    
        ...ack/packer/start/codewindow.nvim/lua/codewindow/text.lua:96: in function 'update_minimap'                                                                                            
        ...ite/pack/packer/start/codewindow.nvim/lua/codewindow.lua:20: in function 'open_minimap'                                                                                              
        ...ite/pack/packer/start/codewindow.nvim/lua/codewindow.lua:13: in function ''                                                                                                          
        vim/_editor.lua: in function ''                                                                                                                                                         
        vim/_editor.lua: in function <vim/_editor.lua:0> 
```

**Comment by gorbit99** [comment]
I cannot for the life of me reproduce this, any way of creating splits and jumping around seems to work just fine for me. Can you provide more details?

**Comment by jemag** [comment]
Happens to me as well, although not every time. 

In my case, if I open the mini-map, scroll around a bit and move my cursor. Then opening a floating terminal with [Floaterm](https://github.com/voldikss/vim-floaterm) might trigger the error:
![image](https://user-images.githubusercontent.com/7985687/196584828-5ff118da-0ba6-457f-83cb-4c3915759843.png)

**Comment by nyngwang** [comment]
> I cannot for the life of me reproduce this

Well, I just encountered this too. I'm at the latested commit of neovim

```
NVIM v0.9.0-dev-135-g96cf385a7
Build type: Release
LuaJIT 2.1.0-beta3
```

**Comment by grappas** [comment]
It just happened to me while entering terminal
Reproductable every time with my macro
`command Terminal :below 7split | terminal`

![obraz](https://user-images.githubusercontent.com/1036957/196803823-9099f075-422c-4b72-8f34-b9c4b6b42049.png)

**Comment by gorbit99** [comment]
Oh great, I can reproduce this. I'll get to it immediately!

**Comment by grappas** [comment]
@gorbit99 it's still rarely happens, but this time I dunno how to reproduce this. I'll try to find the way.
